#define TIMESTAMP_AT_FLASH_SEC  0x00
#define TIMESTAMP_AT_FLASH_MIN  0x6
#define TIMESTAMP_AT_FLASH_HR   0x0
#define TIMESTAMP_AT_FLASH_DAY  0x6
#define TIMESTAMP_AT_FLASH_DATE 0x11
#define TIMESTAMP_AT_FLASH_MON  0x2
#define TIMESTAMP_AT_FLASH_YR   0x23