#define TIMESTAMP_AT_FLASH_SEC  0x00
#define TIMESTAMP_AT_FLASH_MIN  0x38
#define TIMESTAMP_AT_FLASH_HR   0x8
#define TIMESTAMP_AT_FLASH_DAY  0x5
#define TIMESTAMP_AT_FLASH_DATE 0x2
#define TIMESTAMP_AT_FLASH_MON  0x6
#define TIMESTAMP_AT_FLASH_YR   0x23