#define TIMESTAMP_AT_FLASH_SEC  0x00
#define TIMESTAMP_AT_FLASH_MIN  0x45
#define TIMESTAMP_AT_FLASH_HR   0x14
#define TIMESTAMP_AT_FLASH_DAY  0x4
#define TIMESTAMP_AT_FLASH_DATE 0x1
#define TIMESTAMP_AT_FLASH_MON  0x6
#define TIMESTAMP_AT_FLASH_YR   0x23