#include "stdint.h"
#include "i2c.h"

#define MAGNETOMETER_REG_XOUT0			0x00
#define MAGNETOMETER_REG_XOUT1			0x01
#define MAGNETOMETER_REG_XOUT2			0x02
#define MAGNETOMETER_REG_YOUT0			0x03
#define MAGNETOMETER_REG_YOUT1			0x04
#define MAGNETOMETER_REG_YOUT2			0x05
#define MAGNETOMETER_REG_ZOUT0			0x06
#define MAGNETOMETER_REG_ZOUT1			0x07
#define MAGNETOMETER_REG_ZOUT2			0x08
#define MAGNETOMETER_REG_TOUT			0x09
#define MAGNETOMETER_REG_TPH0			0x0A
#define MAGNETOMETER_REG_TPH1	  		0x0B
#define MAGNETOMETER_REG_TU			0x0C
#define MAGNETOMETER_REG_STATUS1		0x18
#define MAGNETOMETER_REG_STATUS2		0x19
#define MAGNETOMETER_REG_ODR			0x1A
#define MAGNETOMETER_REG_INTERNAL_CONTROL_0	0x1B
#define MAGNETOMETER_REG_INTERNAL_CONTROL_1	0x1C
#define MAGNETOMETER_REG_INTERNAL_CONTROL_2	0x1D
#define MAGNETOMETER_REG_ST_X_TH		0x1E
#define MAGNETOMETER_REG_ST_Y_TH		0x1F
#define MAGNETOMETER_REG_ST_Z_TH		0x20
#define MAGNETOMETER_REG_ST_X			0x27
#define MAGNETOMETER_REG_ST_Y			0x28
#define MAGNETOMETER_REG_ST_Z			0x29
#define MAGNETOMETER_REG_PRODUCT_ID		0x39

void magnetometer_take_measurement(void);
void magnetometer_read_measurement(void);
void magnetometer_get_measurement(void);